"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'th' | 'en';

const translations = {
  th: {
    // ── General / Navbar ──────────────────────────────────────
    wasteBank: 'ธนาคารขยะ',
    points: 'คะแนน',
    lightMode: 'โหมดสว่าง',
    darkMode: 'โหมดมืด',
    logout: 'ออกจากระบบ',
    adminSys: 'ระบบผู้ดูแล',
    overview: 'สรุปภาพรวม',
    manageUsers: 'จัดการผู้ใช้',
    wasteTypes: 'ประเภทขยะ',
    finance: 'การเงิน',
    reports: 'สถิติ/ส่งออก',
    messages: 'ข้อความ',
    rewards: 'ของรางวัล',
    settings: 'ตั้งค่า',
    userSys: 'ระบบสมาชิก',
    home: 'หน้าหลัก',
    leaderboard: 'อันดับ',
    redeem: 'แลกของรางวัล',
    history: 'ประวัติการแลก',
    login: 'เข้าสู่ระบบ',
    register: 'สมัครสมาชิก',

    // ── Landing Page ──────────────────────────────────────────
    smartSystem: 'ระบบรีไซเคิลอัจฉริยะ',
    heroTitle1: 'ธนาคาร',
    heroTitle2: 'ขยะ',
    heroSubtitle: 'ร่วมกันสร้างโลกสวยงาม ด้วยการรีไซเคิลขยะ แลกคะแนน รับของรางวัล และช่วยลดก๊าซเรือนกระจก',
    getStarted: 'เริ่มต้นเลย',
    alreadyAccount: 'มีบัญชีแล้ว? เข้าสู่ระบบ',
    features: 'ฟีเจอร์หลัก',
    doMore: 'ทำได้มากกว่า',
    youThink: 'ที่คุณคิด',
    statsMembers: 'สมาชิก',
    statsWeight: 'กิโลกรัมขยะ',
    statsCo2: 'CO₂ ที่ลด (kg)',
    statsRewards: 'ของรางวัล',
    feature1Title: 'รีไซเคิลขยะ',
    feature1Desc: 'นำขยะมาแลกคะแนน พลาสติก กระดาษ โลหะ และอื่นๆ ทุกชิ้นมีคุณค่า',
    feature1Detail: 'รับคะแนนตามน้ำหนักและประเภทของขยะที่นำมาฝาก ระบบคำนวณโดยอัตโนมัติ',
    feature2Title: 'สะสมคะแนน',
    feature2Desc: 'รับคะแนนทุกครั้งที่นำขยะมาฝาก แลกของรางวัลมากมายรอคุณอยู่',
    feature2Detail: 'ติดตามคะแนนสะสมแบบ Real-time ดูประวัติการฝาก และจัดอันดับในชุมชน',
    feature3Title: 'ช่วยโลก',
    feature3Desc: 'ร่วมกันลดก๊าซ CO₂ ทุก 1 กิโลกรัมที่คุณรีไซเคิล ช่วยโลกได้จริง',
    feature3Detail: 'ดูปริมาณ CO₂ ที่คุณช่วยลดได้ และผลกระทบต่อสิ่งแวดล้อมในเชิงตัวเลขจริง',
    hide: 'ซ่อน',
    seeMore: 'ดูเพิ่มเติม',
    readyToChange: 'พร้อมเริ่มต้น',
    changeWorld: 'เปลี่ยนแปลงโลก?',
    freeRegisterDesc: 'สมัครฟรี ไม่มีค่าใช้จ่าย เริ่มสะสมคะแนนได้ทันที',
    freeRegisterBtn: 'สมัครสมาชิกฟรี',
    footerSlogan: 'ร่วมกันรักษ์โลก ทีละชิ้น',

    // ── Reports Page ──────────────────────────────────────────
    reportsTitle: 'รายงานยอดการรับฝากขยะ',
    reportsSubtitle: 'เลือกช่วงเวลาที่ต้องการดูข้อมูล',
    exportPdf: 'ออก PDF',
    preparing: 'กำลังจัดเตรียม...',
    allYearOverView: 'ดูภาพรวมทั้งปี',
    cardWeight: 'ขยะสะสม',
    cardTx: 'ทำรายการ',
    cardCo2: 'ลด CO2 รวม',
    cardUsers: 'สมาชิกทั้งหมด',
    chartLineTitle: 'ปริมาณขยะ',
    chartPieTitle: 'สัดส่วนประเภทขยะ',
    monthly: 'รายเดือน',
    daily: 'รายวัน',
    noData: 'ไม่มีข้อมูล',
    top5Title: '5 อันดับคะแนนสูงสุด',
    historyTableTitle: 'ประวัติการฝาก',
    searchName: 'ค้นชื่อ...',
    colDate: 'วันที่',
    colMember: 'สมาชิก',
    colType: 'ประเภท',
    colWeight: 'กก.',
    pageText: 'หน้า',
    chatBotReady: 'พร้อมรับคำสั่งค่ะ',
    chatBotThinking: 'กำลังวิเคราะห์...',
    chatBotSpeaking: 'กำลังพรีเซนต์...',
    clearChat: 'ล้างหน้าจอแชท',
    typeCommand: 'พิมพ์คำสั่งหรือถามข้อมูล...',
    month: 'เดือน',
    year: 'ปี',
    itemsCount: 'รายการ',

    // ── Chat Memory ───────────────────────────────────────────
    newChat: 'แชทใหม่',
    chatHistory: 'ประวัติแชท',
    searchChat: 'ค้นหาประวัติแชท...',
    today: 'วันนี้',
    previous7Days: '7 วันที่ผ่านมา',
    older: 'เก่ากว่านั้น',
    deleteChatConfirm: 'คุณต้องการลบประวัติแชทนี้ใช่หรือไม่?',
    noChatHistory: 'ไม่มีประวัติแชท',

    // ── Admin Dashboard ───────────────────────────────────────
    welcomeAdmin: 'ยินดีต้อนรับ ผู้ดูแลระบบ',
    adminDesc: 'ภาพรวมสรุปข้อมูลทั้งหมดของระบบธนาคารขยะ',
    allYear: '-- ทุกเดือน --',
    totalMembersDash: 'สมาชิกทั้งหมด',
    totalBalance: 'ยอดเงินคงเหลือ',
    totalWasteStock: 'สต๊อกขยะรวม',
    pendingRedemptions: 'รออนุมัติแลกรางวัล',
    unitPerson: 'คน',
    unitKg: 'กก.',
    unitItems: 'รายการ',
    unitPoints: 'แต้ม',
    recentDeposits: 'การฝากขยะล่าสุด',
    recentRedemptions: 'การแลกรางวัลล่าสุด',
    noRecentItems: 'ยังไม่มีข้อมูล',

    // ── Admin Users ───────────────────────────────────────────
    allMembersAccount: 'บัญชีสมาชิกทั้งหมด',
    registeredMembers1: 'มีสมาชิกลงทะเบียน ',
    registeredMembers2: ' คนในระบบ',
    addPointsTitle: 'เพิ่มคะแนน / รับฝากขยะ',
    editTitle: 'แก้ไขข้อมูล',
    normalBadge: 'ปกติ',
    bannedBadge: 'ระงับ',
    allGender: '-- ทุกเพศ --',
    allStatus: '-- ทุกสถานะ --',
    searchMember: 'ค้นหาสมาชิก...',
    depositTitle: 'รับฝากขยะ',
    noMembersFound: 'ไม่พบสมาชิก',
    // 🟢 Filter bar keys
    scanQrDeposit: 'สแกน QR รับฝากขยะ',
    searchUsersPlaceholder: 'ค้นหาชื่อ / username...',
    allGenders: '-- ทุกเพศ --',
    male: 'ชาย',
    female: 'หญิง',
    notSpecified: 'ไม่ระบุ',
    allStatuses: '-- ทุกสถานะ --',
    activeStatus: 'ปกติ',
    bannedStatus: 'ระงับ',
    noDataFound: 'ไม่พบสมาชิก',
    tryChangeFilter: 'ลองเปลี่ยนเงื่อนไขการค้นหา',
    // Deposit Modal
    wasteDepositSystem: 'ระบบรับฝากขยะ',
    scanCustomerQr: 'สแกน QR ลูกค้า',
    openCameraScanQr: 'เปิดกล้องสแกน QR',
    cancelScan: 'ยกเลิกการสแกน',
    userIdPlaceholder: 'พิมพ์ User ID...',
    searchBtn: 'ค้นหา',
    recordWasteDeposit: 'บันทึกการฝากขยะ',
    openAiCamera: 'เปิดกล้อง AI จำแนกขยะ',
    analyzeImage: 'วิเคราะห์ภาพ',
    thinking: 'กำลังวิเคราะห์...',
    closeCamera: 'ปิดกล้อง',
    aiAnalyzing: 'AI กำลังวิเคราะห์ภาพ...',
    foundWaste: 'พบขยะประเภท:',
    detectedItemPrefix: 'ตรวจพบ:',
    alienObject: 'วัตถุแปลกปลอม',
    notInSystemScanAgain: 'รายการนี้ไม่อยู่ในระบบ กรุณาสแกนใหม่',
    wasteTypeLabel: 'ประเภทขยะ',
    selectWasteType: '-- เลือกประเภทขยะ --',
    ptsPerKg: 'แต้ม/กก.',
    weightLabel: 'น้ำหนัก (กก.)',
    kg: 'กก.',
    pointsToReceive: 'แต้มที่จะได้รับ',
    saving: 'กำลังบันทึก...',
    saveAndNotifyLine: 'บันทึกและแจ้ง LINE',
    saveSuccess: 'บันทึกสำเร็จ!',
    typeWeight: 'ประเภท / น้ำหนัก',
    nextDeposit: 'รับฝากรายถัดไป',
    closeBtn: 'ปิด',
    editUserTitle: 'แก้ไขข้อมูลสมาชิก',
    firstNameLabel: 'ชื่อ',
    lastNameLabel: 'นามสกุล',
    phoneLabel: 'เบอร์โทรศัพท์',
    roleLabel: 'บทบาท',
    pointsLabel: 'คะแนนสะสม',
    statusLabel: 'สถานะ',
    saveChanges: 'บันทึกการเปลี่ยนแปลง',

    // ── Login Page ────────────────────────────────────────────
    backToHome: 'กลับหน้าหลัก',
    welcome: 'ยินดีต้อนรับ',
    loginSubtitle: 'เข้าสู่ระบบเพื่อจัดการบัญชีของคุณ',
    loginEmailLabel: 'อีเมล',
    loginEmailPlaceholder: 'your@email.com',
    loginPasswordLabel: 'รหัสผ่าน',
    loginPasswordPlaceholder: '••••••••',
    forgotPassword: 'ลืมรหัสผ่าน?',
    loginBtn: 'เข้าสู่ระบบ',
    loggingIn: 'กำลังเข้าสู่ระบบ...',
    noAccount: 'ยังไม่มีบัญชี?',
    registerHere: 'สมัครสมาชิกที่นี่',
    recoverPassword: 'กู้คืนรหัสผ่าน',
    recoverSubtitle: 'กรอกอีเมลที่ลงทะเบียนไว้',
    recoverEmailPlaceholder: 'อีเมลที่ลงทะเบียน',
    securityQuestionTitle: 'คำถามเพื่อความปลอดภัย',
    answerPlaceholder: 'กรอกคำตอบของคุณ',
    checkAnswer: 'ยืนยันคำตอบ',
    setNewPassword: 'ตั้งรหัสผ่านใหม่',
    setNewPasswordSubtitle: 'กรอกรหัสผ่านใหม่ที่ต้องการ',
    newPasswordPlaceholder: 'รหัสผ่านใหม่',
    saveNewPassword: 'บันทึกรหัสผ่านใหม่',
    resetSuccess: 'รีเซ็ตรหัสผ่านสำเร็จ!',
    resetSuccessDesc: 'รหัสผ่านของคุณถูกเปลี่ยนแล้ว กำลังพาไปหน้าเข้าสู่ระบบ...',
    back: 'ย้อนกลับ',
    searching: 'กำลังค้นหา...',
    continueBtn: 'ดำเนินการต่อ',
    errLoginNotFound: 'ไม่พบบัญชีผู้ใช้นี้',
    errLoginPassword: 'รหัสผ่านไม่ถูกต้อง',
    errLoginBanned: 'บัญชีนี้ถูกระงับการใช้งาน',
    errEmailNotFound: 'ไม่พบอีเมลนี้ในระบบ',
    errWrongAnswer: 'คำตอบไม่ถูกต้อง',
    errResetFail: 'รีเซ็ตรหัสผ่านไม่สำเร็จ กรุณาลองใหม่',
    errPassword: 'รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร',

    // ── Register Page ─────────────────────────────────────────
    createAccount: 'สร้างบัญชีใหม่',
    joinUsDesc: 'ร่วมเป็นส่วนหนึ่งของการรักษ์โลกวันนี้',
    personalInfo: 'ข้อมูลส่วนตัว',
    contactInfo: 'ข้อมูลติดต่อ',
    accountInfo: 'ข้อมูลบัญชี',
    securityQuestion: 'คำถามเพื่อความปลอดภัย',
    titleLabel: 'คำนำหน้า',
    mr: 'นาย',
    mrs: 'นาง',
    miss: 'นางสาว',
    others: 'อื่นๆ',
    firstName: 'ชื่อ',
    lastName: 'นามสกุล',
    genderLabel: 'เพศ',
    genderNotSpec: 'ไม่ระบุ',
    genderMale: 'ชาย',
    genderFemale: 'หญิง',
    phoneHint: 'ตัวเลข 9-10 หลัก',
    phonePlaceholder: '0812345678',
    emailLabel: 'อีเมล (ตัวเลือก)',
    emailPlaceholder: 'your@email.com',
    usernameLabel: 'ชื่อผู้ใช้',
    usernameHint: 'ตัวอักษร ตัวเลข ขีดล่าง 3-20 ตัว',
    usernamePlaceholder: 'เช่น eco_user01',
    passwordLabel: 'รหัสผ่าน',
    passwordPlaceholder: 'อย่างน้อย 6 ตัว',
    confirmPasswordLabel: 'ยืนยันรหัสผ่าน',
    confirmPasswordPlaceholder: 'พิมพ์ซ้ำอีกครั้ง',
    pwMatch: 'รหัสผ่านตรงกัน',
    pwNoMatch: 'รหัสผ่านไม่ตรงกัน',
    petQuestion: 'ชื่อสัตว์เลี้ยงของคุณคืออะไร?',
    petHint: 'ใช้สำหรับกู้คืนรหัสผ่าน',
    petAnswerPlaceholder: 'เช่น หมาไทย, แมวส้ม',
    registerNow: 'สมัครสมาชิกเลย',
    creatingAccount: 'กำลังสร้างบัญชี...',
    alreadyHaveAccount: 'มีบัญชีอยู่แล้ว?',
    loginHere: 'เข้าสู่ระบบที่นี่',
    registerSuccess: 'สมัครสมาชิกสำเร็จ!',
    registerSuccessDesc: 'บัญชีของคุณถูกสร้างแล้ว กำลังพาไปหน้าเข้าสู่ระบบ...',
    formIncomplete: 'กรุณากรอกข้อมูลให้ครบถ้วนและถูกต้อง',
    usernameTaken: 'ชื่อผู้ใช้นี้ถูกใช้งานแล้ว',
    errFirstname: 'กรุณากรอกชื่อ',
    errLastname: 'กรุณากรอกนามสกุล',
    errPhone: 'เบอร์โทรต้องเป็นตัวเลข 9-10 หลัก',
    errEmail: 'รูปแบบอีเมลไม่ถูกต้อง',
    errUsername: 'ชื่อผู้ใช้ต้องเป็น a-z, 0-9, _ และยาว 3-20 ตัว',
    errConfirmPw: 'รหัสผ่านไม่ตรงกัน',
    errPetName: 'กรุณากรอกชื่อสัตว์เลี้ยง',
    pwStrWeak: 'รหัสผ่านอ่อนแอมาก',
    pwStrFair: 'รหัสผ่านพอใช้ได้',
    pwStrGood: 'รหัสผ่านดี',
    pwStrStrong: 'รหัสผ่านแข็งแกร่งมาก',

    // ── User Dashboard ────────────────────────────────────────
    myPoints: 'คะแนนของฉัน',
    totalRecycled: 'รีไซเคิลแล้ว',
    co2Saved: 'CO₂ ที่ลด',
    myRank: 'อันดับของฉัน',
    outOf: 'จาก',
    people: 'คน',
    redeemRewards: 'แลกของรางวัล',
    redeemHistory: 'ประวัติการแลก',
    leaderboardTitle: 'อันดับผู้รีไซเคิล',
    availableRewards: 'ของรางวัลที่แลกได้',
    searchReward: 'ค้นหาของรางวัล...',
    filterByPoints: 'กรองตามคะแนน...',
    notEnoughPoints: 'คะแนนไม่พอ',
    redeemBtn: 'แลกเลย',
    outOfStock: 'หมดแล้ว',
    noRewardsFound: 'ไม่พบของรางวัล',
    redeemHistoryTitle: 'ประวัติการแลกรางวัล',
    noHistory: 'ยังไม่มีประวัติการแลก',
    pending: 'รอดำเนินการ',
    approved: 'อนุมัติแล้ว',
    rejected: 'ไม่อนุมัติ',
    confirmRedeemTitle: 'ยืนยันการแลก',
    youWillUse: 'คุณจะใช้',
    toRedeem: 'เพื่อแลก',
    yesOrNo: 'ยืนยันหรือไม่?',
    cancel: 'ยกเลิก',
    confirmRedeemBtn: 'ยืนยันแลก',
    contactAdmin: 'ติดต่อแอดมิน',
    askOrReport: 'ถามหรือแจ้งปัญหา',
    typeHere: 'พิมพ์ข้อความ...',
    noMessages: 'ยังไม่มีข้อความ\nส่งข้อความเพื่อเริ่มสนทนากับแอดมิน',
    editProfile: 'แก้ไขโปรไฟล์',
    clickToChangeProfile: 'แตะเพื่อเปลี่ยนรูปโปรไฟล์',
    phone: 'เบอร์โทร',
    myQrCode: 'QR Code ของฉัน',
    downloadQr: 'ดาวน์โหลด QR',
    co2ChartTitle: 'CO₂ ที่ลดในช่วง 5 เดือนล่าสุด',
  },

  en: {
    // ── General / Navbar ──────────────────────────────────────
    wasteBank: 'EcoBit Exchange',
    points: 'Points',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    logout: 'Logout',
    adminSys: 'Admin System',
    overview: 'Dashboard',
    manageUsers: 'Users',
    wasteTypes: 'Waste Types',
    finance: 'Finance',
    reports: 'Reports/Export',
    messages: 'Messages',
    rewards: 'Rewards',
    settings: 'Settings',
    userSys: 'Member System',
    home: 'Home',
    leaderboard: 'Leaderboard',
    redeem: 'Redeem Rewards',
    history: 'History',
    login: 'Login',
    register: 'Sign Up',

    // ── Landing Page ──────────────────────────────────────────
    smartSystem: 'Smart Recycling System',
    heroTitle1: 'EcoBit',
    heroTitle2: 'Exchange',
    heroSubtitle: 'Join us in making the world beautiful by recycling waste. Earn points, get rewards, and help reduce greenhouse gases.',
    getStarted: 'Get Started',
    alreadyAccount: 'Already have an account? Login',
    features: 'Core Features',
    doMore: 'Do more than',
    youThink: 'you think',
    statsMembers: 'Members',
    statsWeight: 'Recycled (kg)',
    statsCo2: 'CO₂ Reduced (kg)',
    statsRewards: 'Rewards',
    feature1Title: 'Recycle Waste',
    feature1Desc: 'Exchange waste for points. Plastic, paper, metal, and more.',
    feature1Detail: 'Earn points based on weight and type. Calculated automatically.',
    feature2Title: 'Earn Points',
    feature2Desc: 'Get points every time you recycle. Awesome rewards await.',
    feature2Detail: 'Track points in real-time, view history, and check leaderboards.',
    feature3Title: 'Save the Earth',
    feature3Desc: 'Reduce CO₂ with every kilogram recycled. Make a real impact.',
    feature3Detail: 'See the exact amount of CO₂ you helped reduce in real numbers.',
    hide: 'Hide',
    seeMore: 'See More',
    readyToChange: 'Ready to',
    changeWorld: 'Change the World?',
    freeRegisterDesc: 'Free to join. Start earning points today.',
    freeRegisterBtn: 'Sign Up for Free',
    footerSlogan: 'Saving the planet, one piece at a time',

    // ── Reports Page ──────────────────────────────────────────
    reportsTitle: 'Waste Deposit Reports',
    reportsSubtitle: 'Select a time period to view data',
    exportPdf: 'Export PDF',
    preparing: 'Preparing...',
    allYearOverView: 'View All Year',
    cardWeight: 'Total Waste',
    cardTx: 'Transactions',
    cardCo2: 'Total CO2 Reduced',
    cardUsers: 'Total Members',
    chartLineTitle: 'Waste Volume',
    chartPieTitle: 'Waste Proportions',
    monthly: 'Monthly',
    daily: 'Daily',
    noData: 'No data',
    top5Title: 'Top 5 Highest Points',
    historyTableTitle: 'Deposit History',
    searchName: 'Search...',
    colDate: 'Date',
    colMember: 'Member',
    colType: 'Type',
    colWeight: 'kg',
    pageText: 'Page',
    chatBotReady: 'Ready for your command',
    chatBotThinking: 'Thinking...',
    chatBotSpeaking: 'Presenting...',
    clearChat: 'Clear Screen',
    typeCommand: 'Type command or ask...',
    month: 'Month',
    year: 'Year',
    itemsCount: 'items',

    // ── Chat Memory ───────────────────────────────────────────
    newChat: 'New Chat',
    chatHistory: 'Chat History',
    searchChat: 'Search history...',
    today: 'Today',
    previous7Days: 'Previous 7 Days',
    older: 'Older',
    deleteChatConfirm: 'Are you sure you want to delete this chat?',
    noChatHistory: 'No chat history',

    // ── Admin Dashboard ───────────────────────────────────────
    welcomeAdmin: 'Welcome, Administrator',
    adminDesc: 'Overview of all waste bank system data',
    allYear: '-- All Months --',
    totalMembersDash: 'Total Members',
    totalBalance: 'Net Balance',
    totalWasteStock: 'Total Waste Stock',
    pendingRedemptions: 'Pending Redemptions',
    unitPerson: 'people',
    unitKg: 'kg',
    unitItems: 'items',
    unitPoints: 'pts',
    recentDeposits: 'Recent Deposits',
    recentRedemptions: 'Recent Redemptions',
    noRecentItems: 'No data yet',

    // ── Admin Users ───────────────────────────────────────────
    allMembersAccount: 'All Member Accounts',
    registeredMembers1: '',
    registeredMembers2: ' members registered',
    addPointsTitle: 'Add Points / Accept Deposit',
    editTitle: 'Edit',
    normalBadge: 'Active',
    bannedBadge: 'Banned',
    allGender: '-- All Genders --',
    allStatus: '-- All Status --',
    searchMember: 'Search members...',
    depositTitle: 'Waste Deposit',
    noMembersFound: 'No members found',
    // 🟢 Filter bar keys
    scanQrDeposit: 'Scan QR Deposit',
    searchUsersPlaceholder: 'Search name / username...',
    allGenders: '-- All Genders --',
    male: 'Male',
    female: 'Female',
    notSpecified: 'Not specified',
    allStatuses: '-- All Statuses --',
    activeStatus: 'Active',
    bannedStatus: 'Banned',
    noDataFound: 'No members found',
    tryChangeFilter: 'Try adjusting your search filters',
    // Deposit Modal
    wasteDepositSystem: 'Waste Deposit System',
    scanCustomerQr: 'Scan Customer QR',
    openCameraScanQr: 'Open Camera to Scan QR',
    cancelScan: 'Cancel Scan',
    userIdPlaceholder: 'Enter User ID...',
    searchBtn: 'Search',
    recordWasteDeposit: 'Record Waste Deposit',
    openAiCamera: 'Open AI Waste Camera',
    analyzeImage: 'Analyze Image',
    thinking: 'Analyzing...',
    closeCamera: 'Close Camera',
    aiAnalyzing: 'AI is analyzing the image...',
    foundWaste: 'Waste found:',
    detectedItemPrefix: 'Detected:',
    alienObject: 'Unknown object',
    notInSystemScanAgain: 'Item not in system. Please scan again.',
    wasteTypeLabel: 'Waste Type',
    selectWasteType: '-- Select Waste Type --',
    ptsPerKg: 'pts/kg',
    weightLabel: 'Weight (kg)',
    kg: 'kg',
    pointsToReceive: 'Points to receive',
    saving: 'Saving...',
    saveAndNotifyLine: 'Save & Notify LINE',
    saveSuccess: 'Saved Successfully!',
    typeWeight: 'Type / Weight',
    nextDeposit: 'Next Deposit',
    closeBtn: 'Close',
    editUserTitle: 'Edit Member',
    firstNameLabel: 'First Name',
    lastNameLabel: 'Last Name',
    phoneLabel: 'Phone Number',
    roleLabel: 'Role',
    pointsLabel: 'Points',
    statusLabel: 'Status',
    saveChanges: 'Save Changes',

    // ── Login Page ────────────────────────────────────────────
    backToHome: 'Back to Home',
    welcome: 'Welcome Back',
    loginSubtitle: 'Log in to manage your account',
    loginEmailLabel: 'Email',
    loginEmailPlaceholder: 'your@email.com',
    loginPasswordLabel: 'Password',
    loginPasswordPlaceholder: '••••••••',
    forgotPassword: 'Forgot password?',
    loginBtn: 'Log In',
    loggingIn: 'Logging in...',
    noAccount: "Don't have an account?",
    registerHere: 'Register here',
    recoverPassword: 'Recover Password',
    recoverSubtitle: 'Enter your registered email address',
    recoverEmailPlaceholder: 'Registered email',
    securityQuestionTitle: 'Security Question',
    answerPlaceholder: 'Enter your answer',
    checkAnswer: 'Verify Answer',
    setNewPassword: 'Set New Password',
    setNewPasswordSubtitle: 'Enter your new password',
    newPasswordPlaceholder: 'New password',
    saveNewPassword: 'Save New Password',
    resetSuccess: 'Password Reset Successful!',
    resetSuccessDesc: 'Your password has been changed. Redirecting to login...',
    back: 'Back',
    searching: 'Searching...',
    continueBtn: 'Continue',
    errLoginNotFound: 'Account not found',
    errLoginPassword: 'Incorrect password',
    errLoginBanned: 'This account has been suspended',
    errEmailNotFound: 'Email not found in the system',
    errWrongAnswer: 'Incorrect answer',
    errResetFail: 'Password reset failed. Please try again.',
    errPassword: 'Password must be at least 6 characters',

    // ── Register Page ─────────────────────────────────────────
    createAccount: 'Create Account',
    joinUsDesc: 'Join the planet-saving movement today',
    personalInfo: 'Personal Info',
    contactInfo: 'Contact Info',
    accountInfo: 'Account Info',
    securityQuestion: 'Security Question',
    titleLabel: 'Title',
    mr: 'Mr.',
    mrs: 'Mrs.',
    miss: 'Ms.',
    others: 'Other',
    firstName: 'First Name',
    lastName: 'Last Name',
    genderLabel: 'Gender',
    genderNotSpec: 'Not specified',
    genderMale: 'Male',
    genderFemale: 'Female',
    phoneHint: '9-10 digit number',
    phonePlaceholder: '0812345678',
    emailLabel: 'Email (optional)',
    emailPlaceholder: 'your@email.com',
    usernameLabel: 'Username',
    usernameHint: 'Letters, numbers, underscore, 3-20 chars',
    usernamePlaceholder: 'e.g. eco_user01',
    passwordLabel: 'Password',
    passwordPlaceholder: 'At least 6 characters',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: 'Re-enter password',
    pwMatch: 'Passwords match',
    pwNoMatch: 'Passwords do not match',
    petQuestion: "What is your pet's name?",
    petHint: 'Used for password recovery',
    petAnswerPlaceholder: 'e.g. Buddy, Whiskers',
    registerNow: 'Register Now',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Log in here',
    registerSuccess: 'Registration Successful!',
    registerSuccessDesc: 'Your account has been created. Redirecting to login...',
    formIncomplete: 'Please fill in all required fields correctly',
    usernameTaken: 'This username is already taken',
    errFirstname: 'First name is required',
    errLastname: 'Last name is required',
    errPhone: 'Phone must be 9-10 digits',
    errEmail: 'Invalid email format',
    errUsername: 'Username must be a-z, 0-9, _ and 3-20 characters',
    errConfirmPw: 'Passwords do not match',
    errPetName: "Pet's name is required",
    pwStrWeak: 'Very weak',
    pwStrFair: 'Fair',
    pwStrGood: 'Good',
    pwStrStrong: 'Strong',

    // ── User Dashboard ────────────────────────────────────────
    myPoints: 'My Points',
    totalRecycled: 'Recycled',
    co2Saved: 'CO₂ Saved',
    myRank: 'My Rank',
    outOf: 'out of',
    people: 'people',
    redeemRewards: 'Redeem Rewards',
    redeemHistory: 'Redemption History',
    leaderboardTitle: 'Recycler Leaderboard',
    availableRewards: 'Available Rewards',
    searchReward: 'Search rewards...',
    filterByPoints: 'Filter by points...',
    notEnoughPoints: 'Not enough points',
    redeemBtn: 'Redeem',
    outOfStock: 'Out of stock',
    noRewardsFound: 'No rewards found',
    redeemHistoryTitle: 'Redemption History',
    noHistory: 'No redemption history yet',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    confirmRedeemTitle: 'Confirm Redemption',
    youWillUse: 'You will use',
    toRedeem: 'to redeem',
    yesOrNo: 'Confirm?',
    cancel: 'Cancel',
    confirmRedeemBtn: 'Confirm',
    contactAdmin: 'Contact Admin',
    askOrReport: 'Ask or report an issue',
    typeHere: 'Type a message...',
    noMessages: 'No messages yet\nSend a message to start chatting with admin',
    editProfile: 'Edit Profile',
    clickToChangeProfile: 'Tap to change profile photo',
    phone: 'Phone',
    myQrCode: 'My QR Code',
    downloadQr: 'Download QR',
    co2ChartTitle: 'CO₂ Saved Over Last 5 Months',
  },
};

interface LanguageContextType {
  lang: Language;
  toggleLang: () => void;
  t: (key: keyof typeof translations['th']) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>('th');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    const savedLang = localStorage.getItem('app_lang') as Language;
    if (savedLang) setLang(savedLang);
    setMounted(true);
  }, []);

  const toggleLang = () => {
    const newLang = lang === 'th' ? 'en' : 'th';
    setLang(newLang);
    localStorage.setItem('app_lang', newLang);
  };

  const t = (key: keyof typeof translations['th']): string => {
    return translations[lang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      <div suppressHydrationWarning>{children}</div>
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};